name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Electron Forge Action
        # You may pin to the exact commit or the version.
        # uses: yinxulai/actions-electron-forge@456a6517c5241e4d693507b99a30dac8fe622102
        uses: yinxulai/actions-electron-forge@0.05
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          # Directory where NPM/Yarn commands should be run
          package_root: .
          # Optional package.json scripts name
          script_name: # optional, default is publish
          # Whether the app should be released after a successful build
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
